Remove ansible_user option
The README describes running Ansible from mgmtvm instead of dom0, but
the `-u` option is disallowed from domUs:

```console
mgmtvm$ qvm-run --pass-io --service -u user workvm qubes.VMShell
...
ValueError: non-default user not possible for calls from VM
```

This change unifies the interface for running tasks as non-default users
on dom0 and domUs under the qubes_shell_rpc option.